agp_rel:
    resource: "@AgpRelBundle/Controller/"
    type:     annotation
    prefix:   /

agp_admin:
    resource: "@AgpAdminBundle/Controller/"
    type:     annotation
    prefix:   /

agp_front:
    resource: "@AgpFrontBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
