jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Agp\AdminBundle\Entity\Pessoa: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        entity_user:
            entity: { class: AgpAdminBundle:Pessoa, property: email }
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            pattern:  ^/login$
            security: false
            
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario, roles: ROLE_USUARIO }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USUARIO] }

#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/usuario/
#            form_login:
#                check_path: /usuario/login_check
#                login_path: /usuario/login
#                default_target_path: /
#            logout:
#                path:   /usuario/logout
#                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
#
#    access_control:
#        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
