<?php

namespace Agp\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TerminalEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradaProdutoRepository extends EntityRepository
{ 
    public function getProdutosHabilitados($produto, $fornecedor, $dtInicio, $dtTermino, $user){
        
        $dtInicio = new \DateTime($this->conv_data_to_us($dtInicio));
        $dtInicio->format("Y-m-d");
        
        $dtTermino = new \DateTime($this->conv_data_to_us($dtTermino));
        $dtTermino->format("Y-m-d");
        
        $qb = $this->createQueryBuilder("ep")
            ->select("ep.dtEntrada dtEntrada, p.nome produto, p.codProduto codProduto, ep.qtde qtde, ep.vlrCusto custo, f.razaoSocial fornecedor")
            ->join("ep.produto", "p")
            ->join("ep.fornecedor", "f")
            ->where("p.empresa = :empresa")
            ->andWhere("ep.dtEntrada BETWEEN :dtInicio AND :dtTermino")
            ->setParameters(array("empresa" => $user->getEmpresa(),
                                  "dtInicio" => $dtInicio,
                                  "dtTermino" => $dtTermino));
        
        if ($produto != 0){
            $qb->andwhere("p.codProduto = :produto")
               ->setParameter("produto", $produto);
        }
        
        if ($fornecedor != 0){
            $qb->andwhere("f.codFornecedor = :produto")
               ->setParameter("produto", $produto);
        }

        $entities['aaData'] = $qb->getQuery()->getArrayResult();  
     
        return $entities;
    }
    
    public static function conv_data_to_us($date){
	$dia = substr($date,0,2);
	$mes = substr($date,3,2);
	$ano = substr($date,6,4);
	return "{$ano}-{$mes}-{$dia}";
    }
}