<?php

namespace Agp\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Agp\AdminBundle\Entity\TerminalEmpresa;

/**
 * TerminalEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabilitaProdutoTerminalRepository extends EntityRepository
{
    public function clearProdutosHabilitados($terminalEmpresa)
    {
        return  $this->createQueryBuilder("hpt")
                ->delete()
                ->where("hpt.terminalEmpresa = :terminalEmpresa")
                ->setParameters(array("terminalEmpresa" => $terminalEmpresa))
                ->getQuery()
                ->getResult();
    }

    public function getHabilitaProdutoTerminalByTerminal($terminalEmpresa)
    {
        return $this->createQueryBuilder("hpt")
                ->select("hpt, plp, p")
                ->join("hpt.produtoListaPreco", "plp")
                ->join("plp.produto", "p")
                ->where("hpt.terminalEmpresa = :terminalEmpresa")
                ->setParameters(array("terminalEmpresa" => $terminalEmpresa))
                ->getQuery()
                ->getArrayResult();
    }
}