<?php

namespace Agp\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Agp\AdminBundle\Entity\TerminalEmpresa;

/**
 * TerminalEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminalEmpresaRepository extends EntityRepository
{
    public function getCountTerminalAtivo($id){
        
        return  $this->createQueryBuilder("te")
            ->select("count(te.codTerminalEmpresa)")
            ->join("te.terminal", 't')
            ->where("t.codTerminal = :id")
            ->andWhere("te.situacao = :param")
            ->setParameters(array("id" => $id,
                                  "param" => TerminalEmpresa::SIT_ATIVO))
            ->getQuery()
            ->getSingleScalarResult();
    }
    
}