<?php

namespace Agp\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * vendaGeralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendaGeralRepository extends EntityRepository
{
    public function getVendas($pessoa, $terminal, $fechamento){
        
        $qb = $this->createQueryBuilder("v")
            ->select("v.numFechamento, v.nomeProduto, v.qtdeTotal, v.vlrTotal, t.codTerminal")
            ->join("v.terminal", 't')
            ->where("v.empresa = :empresa")
            ->setParameters(array("empresa" => $pessoa->getEmpresa()));
        
        if ($terminal != 0){
            $qb->andwhere("t.codTerminal = :terminal")
               ->setParameter("terminal", $terminal);
        }
        
        if ($fechamento != 0){
            $qb->andwhere("v.numFechamento = :fechamento")
               ->setParameter("fechamento", $fechamento);
        }

        $vendas['aaData'] = $qb->getQuery()->getArrayResult();           
        return $vendas;
    }
    
    public function getVendasByTerminal($pessoa, $terminal, $fechamento){
        
        $qb = $this->createQueryBuilder("v")
            ->select("t.codTerminal, v.numFechamento, sum(v.qtdeTotal) as qtdeTotal, sum(v.vlrTotal) as vlrTotal, v.nomeProduto")
            ->join("v.terminal", 't')
            ->where("v.empresa = :empresa")
            ->addGroupBy("v.terminal")
            ->setParameters(array("empresa" => $pessoa->getEmpresa()));
        
        if ($terminal != 0){
            $qb->andwhere("t.codTerminal = :terminal")
               ->setParameter("terminal", $terminal);
        }
        
        if ($fechamento != 0){
            $qb->andwhere("v.numFechamento = :fechamento")
               ->setParameter("fechamento", $fechamento);
        }

        $vendas['aaData'] = $qb->getQuery()->getArrayResult();  
     
        return $vendas;
    }
    
    public function getVendasByProduto($pessoa, $terminal, $fechamento){
        
        $qb = $this->createQueryBuilder("v")
            ->select("t.codTerminal, v.numFechamento, sum(v.qtdeTotal) as qtdeTotal, sum(v.vlrTotal) as vlrTotal, v.nomeProduto")
            ->join("v.terminal", 't')
            ->where("v.empresa = :empresa")
            ->addGroupBy("v.nomeProduto")
            ->setParameters(array("empresa" => $pessoa->getEmpresa()));
        
        if ($terminal != 0){
            $qb->andwhere("t.codTerminal = :terminal")
               ->setParameter("terminal", $terminal);
        }
        
        if ($fechamento != 0){
            $qb->andwhere("v.numFechamento = :fechamento")
               ->setParameter("fechamento", $fechamento);
        }

        $vendas['aaData'] = $qb->getQuery()->getArrayResult();  
     
        return $vendas;
    }
    
    public function getFechamento($pessoa){
        
        $qb = $this->createQueryBuilder("v")
            ->select("distinct(v.numFechamento)")
            ->where("v.empresa = :empresa")
            ->setParameters(array("empresa" => $pessoa->getEmpresa()));
        
        $fechamentos['options'] = array();
        foreach ($qb->getQuery()->getArrayResult() as $num){
            $fechamentos['options'][$num["numFechamento"]] = str_pad($num["numFechamento"], 4, "0", STR_PAD_LEFT);
        }
        
        $qb2 = $this->createQueryBuilder("v")
            ->select("max(v.numFechamento)")
            ->where("v.empresa = :empresa")
            ->setParameters(array("empresa" => $pessoa->getEmpresa()));
        
        $result = $qb2->getQuery()->getSingleResult();
        $fechamentos["max"] = $result[1];  
        
        return $fechamentos;  
        
    }
    
    public function getTerminal($pessoa){
        
        $qb = $this->createQueryBuilder("v")
            ->select("distinct(t.codTerminal)")
            ->join("v.terminal", "t")
            ->where("v.empresa = :empresa")
            ->setParameters(array("empresa" => $pessoa->getEmpresa()));
        
        $terminais['options'] = array();
        foreach ($qb->getQuery()->getArrayResult() as $num){
            $terminais['options'][$num["codTerminal"]] = str_pad($num["codTerminal"], 4, "0", STR_PAD_LEFT);
        }
        
        return $terminais;  
        
    }
    
}